### ISSUE TITLE
github(issue): criar templates para as issues

### ISSUE THREAD

**Issue by mateusvrs** [unb-mds/2023-2-Squad11#1]
## Issue Templates

**O que são `issue templates`?**
Issue templates são modelos pré-definidos para relatar problemas e solicitar recursos em repositórios. Eles padronizam a criação de issues, facilitando a coleta de informações essenciais.

**Qual é a motivação?**
A motivação para usar issue templates é padronizar relatórios de problemas e solicitações de recursos, melhorando a clareza e a organização nas interações com a comunidade de desenvolvimento, tornando o processo mais eficiente e eficaz.

**Como será feito?**

- [x] Criar as pastas padrões `.github` e `ISSUE_TEMPLATE`.
- [x] Desenvolver os templates `feature-request`, `docs-repair` e `bug-report`.
- [x] Adicionar o template `rabbit`.

**Comment by caio-felipee** [comment]
Está faltando o desenvolvimento do template `rabbit`, com o objetivo de direcionar os contribuidores com conteúdo de estudos pré-definidos.

**Comment by mateusvrs** [comment]
> Está faltando o desenvolvimento do template `rabbit`, com o objetivo de direcionar os contribuidores com conteúdo de estudos pré-definidos.

Ok. Irei adicionar!
