### ISSUE TITLE
Tema Livre: Sua Grade UnB

### ISSUE THREAD

**Issue by GabrielCastelo-31** [unb-mds/2023-2-Squad11#18]
# Descrição do projeto
O Sua Grade UnB é um projeto que tem como objetivo auxiliar os alunos da Universidade de Brasília a montarem suas grades horárias de forma mais fácil e intuitiva.
# Contextualização 
Para muitos alunos, especialmente os que estão ingressando, montar uma grade horária pode ser um desafio, dada a ampla oferta de disciplinas, horários, professores e conflitos que podem surgir. Com isso em mente, surge a necessidade de um instrumento que facilite essa tarefa, otimizando o processo e garantindo que os estudantes possam extrair o máximo de sua experiência acadêmica. Assim, apresentamos o aplicativo "Sua Grade UnB".
</br>

# Funcionalidades Gerais
## Personalização e Eficiência:
O aplicativo "Minha Grade UnB" permite que os alunos insiram suas preferências em relação a horários, professores e disciplinas. Ao fazer isso, ele automaticamente gera opções de grades horárias que atendam a esses critérios. Isso evita que o estudante perca tempo tentando manualmente encaixar disciplinas, minimizando conflitos e otimizando a sua rotina.

## Adaptação às Mudanças:
A grade de uma universidade está em constante mudança. Novas disciplinas são oferecidas, horários são ajustados e professores variam a cada semestre. O aplicativo se atualiza constantemente com essas mudanças, garantindo que o aluno sempre tenha as informações mais recentes à disposição.
# Arquitetura do projeto

 - Design: Figma

- Framework: Flutter

- Micro-serviços (API):
     - Python:
       - Django
       - Django REST Framework
- Banco de dados: Amazon RDS PostgreSQL
- Message Queue:
   - Celery
   - Amazon SQS
- DevOps:
   - Docker + Kubernetes
- CI/CD GitHub
- Codecov
- Servidor:
   - EC2 AWS

### Setores:

- **Mobile + Design:**
     @artrsousa1  
     @CaioHabibe 
- **Back-end (API):**
    @GabrielCastelo-31
    @henriquecq
- **DevOps:**
    @caio-felipee
    @mateusvrs

**Comment by mateusvrs** [comment]
O tema foi habilitado pela @RochaCarla no dia 20/09/2023.
