### ISSUE TITLE
Estudo sobre metodologias ágeis

### ISSUE THREAD

**Issue by caio-felipee** [unb-mds/2023-2-Squad11#3]
## Como acelerar o Aprendizado e Disseminar a Cultura de Inovação Ágil

**O que é?**
Com o objetivo de aumentar a produtividade e acelerar o aprendizado de novas ideias e abordagens, será discutido tecnologias como o Scrum e Kanban.

**Como funciona?**
Ao fazer uma leitura do livro de @RochaCarla — "Como Acelerar o Aprendizado e Disseminar a Cultura de Inovação Ágil" — o coelho fará um breve resumo dos principais tópicos que melhorará o desempenho do time em geral.

**Quem será o coelho?**
Caio Felipe, @caio-felipee.

**Tópicos a serem estudados:**

- [x] Objetivo das metodologias
- [x] Onboarding
- [x] Descrição sobre o Scrum
- [x] Como poderá ser aplicado em nosso projeto

**Notion de estudo:**
[Clique aqui](https://wholesale-passenger-a1f.notion.site/Aprendizado-e-Dissemina-o-a-Cultura-de-Inova-o-gil-bb8a63c99cda47c7b4c4f4145a49c0dc?pvs=4)

**Comment by artrsousa1** [comment]
Boa tarde, Caio! Gostaria de propor o uso do Trello para a organização do material de estudo e as demais tasks do projeto.

**Comment by caio-felipee** [comment]
Apresentação e criação de conteúdo concluída com sucesso.

**Comment by GabrielCastelo-31** [comment]
Caio, o link do notion não está funcionando, poderia verificar?

**Comment by caio-felipee** [comment]
> Caio, o link do notion não está funcionando, poderia verificar?

Corrigido!
