### ISSUE TITLE
docker(container): erro de inicialização do container

### ISSUE THREAD

**Issue by caio-felipee** [unb-mds/2023-2-Squad11#35]
**Descreva o erro**
Ao inicializar o container Docker, um erro é reportado:

```
2023-2-squad11-api-1  | python3: can't open file '/app/manage.py': [Errno 2] No such file or directory
```

**Para Reproduzir**
Passos para reproduzir o comportamento:

1. Ir para a pasta do projeto
2. No terminal, executar o comando `docker compose up`
3. Espere a instalação das dependências
4. Ver o erro

**Comportamento esperado**
Após a instalação de todas as dependências do projeto, ao ser iniciado, o erro é reproduzido. O comportamento esperado era o projeto ser iniciado sem problemas, sem ter a interrupção. Nas versões anteriores, o aplicativo funcionava como esperado. Logo, me leva a suspeita de que o problema não seja na minha máquina.

**Comment by mateusvrs** [comment]
Não consegui reproduzir o erro, poderiamos conversar melhor sobre?

**Comment by caio-felipee** [comment]
Ao conversar com o @mateusvrs, o bug foi solucionado. Conforme as atualizações do aplicativo foram feitas, mais especificamente no Docker, o uso do comando `docker compose up` provavelmente reaproveitou partes do aplicativo da versão antiga. 

Portanto, ao utilizar o comando: 
```sh
docker compose up --build
```

O problema foi solucionado.
