### ISSUE TITLE
Git e GitHub

### ISSUE THREAD

**Issue by GabrielCastelo-31** [unb-mds/2023-2-Squad11#4]
## Git e Github

**O que é?**
**Git** é um sistema de controle de versão distribuído amplamente utilizado para rastrear e gerenciar mudanças em projetos de software.
**GitHub**  é uma plataforma de hospedagem de código-fonte que utiliza o Git como sistema de controle de versão subjacente. 

**Como funciona?**
O **Git** permite que desenvolvedores colaborem em código-fonte, acompanhem o histórico de alterações, resolvam conflitos e revertam para versões anteriores de um projeto de forma eficiente.
Já o **GitHub** oferece recursos adicionais, como rastreamento de problemas, colaboração em equipe, integração contínua e hospedagem de projetos de código aberto e privados.

**Quem será o coelho?**
Gabriel Castelo

**Tópicos a serem estudados:**

- [x] Como clonar um repositório
- [x] Como mudar de Branch
- [x] Como criar uma Branch
- [x] Como gerenciar o código em uma branch
- [x] Como fazer um commit
- [x] Como descartar todas as alterações

**Notion de estudo:**
Duas opções de link. O 1º é para quem não tem conta no Notion.
- https://persistent-dormouse-23f.notion.site/Resumo-Git-e-Github-3d0e8a96af1a49c58e1b56b9a0f808a5?pvs=4 
- https://www.notion.so/Resumo-Git-e-Github-3d0e8a96af1a49c58e1b56b9a0f808a5?pvs=4

**Comment by mateusvrs** [comment]
Muito bom @GabrielCastelo-31!
Só de abrir já vi algumas coisas novas que nunca tinha estudado, será bastante útil o resumo :+1:.

**Comment by CaioHabibe** [comment]
Ótimo material e explicação @GabrielCastelo-31, lendo aqui ja aprendi bastante!
