### ISSUE TITLE
docs(story): criar story map para descrever o flow do projeto

### ISSUE THREAD

**Issue by mateusvrs** [unb-mds/2023-2-Squad11#51]
## Story Map

**Descrição**
Usar o [miro](https://miro.com/) para fazer o story map do projeto

**Escopo**
Relaciona-se com o escopo de **documentação**.

**Tópicos para conclusão da tarefa:**

- [x] Criar conta no miro.
- [x] Passar tasks do **GitHub Projects** para o miro.

**Comment by artrsousa1** [comment]
**[Link para o board da equipe](https://miro.com/app/board/uXjVNYnku7s=/?share_link_id=895311522860)**
