### ISSUE TITLE
(devops): Adicionar bibliotecas Pytest e Pytest-django ao projeto

### ISSUE THREAD

**Issue by GabrielCastelo-31** [unb-mds/2023-2-Squad11#54]
## Adicionar bibliotecas Pytest e Pytest-django ao projeto

**Descrição**
Necessário adicionar essas bibliotecas ao nosso ambiente de trabalho:
- [Pytest](https://docs.pytest.org/en/7.4.x/)
- [pytest-django](https://pytest-django.readthedocs.io/en/latest/)

**Escopo**
Escopo de configuração de ambiente. Relacionado a DevOps

**Tópicos para conclusão da tarefa:**

- [ ] Instalação do [Pytest](https://docs.pytest.org/en/7.4.x/)
- [ ] Instalação do [pytest-django](https://pytest-django.readthedocs.io/en/latest/)

**Comment by mateusvrs** [comment]
No momento não é necessário a adição dessas bibliotecas no projeto, é possível executar os tests necessários da API utilizando os módulos `APITestCase` e `TestCase`, cada um respectivamente do `rest_framework.test` e do `django.test`.
