### ISSUE TITLE
task(Web Scraping): Salvar disciplinas e turmas no banco de dados

### ISSUE THREAD

**Issue by GabrielCastelo-31** [unb-mds/2023-2-Squad11#61]
## Realizar salvamento dos dados obtidos via Web Scraping

**Descrição**
A tarefa consiste em salvar no banco de dados as informações obtidas por meio do web scraping  O web scraping já foi implementado para coletar informações sobre disciplinas e turmas.

**Escopo**
O foco dessa tarefa é a etapa de armazenamento das informações coletadas via Web Scraping, em um formato estruturado no banco de dados, para que possam ser acessadas e utilizadas posteriormente.
**Tópicos para conclusão da tarefa:**

- [x] Escrever testes unitários referentes as models para salvamento de dados
- [x] #78 
- [x] Inserir os dados: Escrever código para inserir os dados coletados do web scraping no banco de dados. Certificar-se de que os dados sejam inseridos de forma consistente e segura.
- [x] Realizar os testes e corrigir possíveis erros.

**Comment by mateusvrs** [comment]
:+1: :tada:
