### ISSUE TITLE
test(Updatedb): Escrever testes para o comando _updatedb_

### ISSUE THREAD

**Issue by GabrielCastelo-31** [unb-mds/2023-2-Squad11#78]
## Escrever testes referente ao código do comando _updatedb_

**Descrição**
A tarefa consiste em escrever testes unitários para validar o funcionamento do comando _updatedb_

**Escopo**
A tarefa está relacionada a escrever código de testes para o comando _updatedb_

**Tópicos para conclusão da tarefa:**
Escrever testes sobre:
- [ ] Popular banco de dados com período atual e período seguinte
- [ ] Criação dos departamentos e disciplinas
- [ ] Criação/Deleção das turmas de uma disciplina
- [ ] Deletar o período anterior
- [ ] Deletar o período atual
- [ ] Deletar o período seguinte
- [ ] Deletar ambos os períodos

**Comment by caio-felipee** [comment]
Testes do comando não serão testados.
