### ISSUE TITLE
docs(mkdocs): criar template para descrição e fechamento das sprints

### ISSUE THREAD

**Issue by mateusvrs** [unb-mds/2023-2-Squad11#8]
## Template para Sprints

**Descrição**
Deve-se criar um template de documentação para definir, descrever e fechar as sprints.

**Escopo**
Documentação do projeto

**Tópicos para conclusão da tarefa:**

- [x] Criar o arquivo `sprint-template.md`
- [x] Definir espaços para:
    - [x] Título
    - [x] Descrição
    - [x] Objetivos
    - [x] Reuniões
    - [x] Finalização 
- [x] Abrir espaço para as *descobertas da semana*

**Comment by caio-felipee** [comment]
Boa tarde. Me confirma uma informação, por favor: as Sprints não devem ser feitas através da opção "Milestone" do GitHub, ao invés de ser uma issue?

**Comment by mateusvrs** [comment]
> Boa tarde. Me confirma uma informação, por favor: as Sprints não devem ser feitas através da opção "Milestone" do GitHub, ao invés de ser uma issue?

Bem pontuado Caio! Podemos organizar as issues de cada Sprint pela `Milestone`, então vou apenas tranferir o template para o site de documentação, visto que ainda devemos descrever e documentar as ações da Sprint mais formalmente, o que acha?

**Comment by caio-felipee** [comment]
> Bem pontuado Caio! Podemos organizar as issues de cada Sprint pela `Milestone`, então vou apenas tranferir o template para o site de documentação, visto que ainda devemos descrever e documentar as ações da Sprint mais formalmente, o que acha?

Me parece ótimo! Realmente devemos realizar a documentação das Sprints.
