### ISSUE TITLE
task(schedules): Gerador de grades

### ISSUE THREAD

**Issue by caio-felipee** [unb-mds/2023-2-Squad11#90]
## Sistema de criação de grades

**Descrição**
O projeto propõe desenvolver um sistema de criação de grades para um período letivo na Universidade de Brasília (UnB). O sistema permitirá aos usuários criar suas grades com base em especificações fornecidas, tornando o processo de seleção de disciplinas mais intuitivo e eficiente.

**Escopo**
A criação das grades será guiada por especificações predefinidas, proporcionando aos usuários a flexibilidade de personalizar seus horários de acordo com suas preferências e requisitos acadêmicos. O sistema será projetado para lidar com diferentes variáveis, como horários, professores, salas e requisitos específicos de cada curso.

**Tópicos para conclusão da tarefa:**

- [x] Permitir que o usuário tenha escolha de prioridade de turno
- [x] Garantir que o usuário receba todas as matérias selecionadas
- [x] Limitar o número de escolha de matérias para no mínimo 1, máximo 11
- [x] Limitar o número de escolha de horários para cada matéria para no mínimo 1, máximo 4
- [x] Garantir que o conteúdo recebido através da requisição seja válido (não gere erros para criação)
- [x] Garantir que todas as informações cruciais recebidas através das requisições estejam presentes.
- [x] Retornar 5 opções (caso houver) de grades para o usuário
- [x] Realizar testes para as funções adicionadas

**Comment by henriquecq** [comment]
:smoking:
